apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-barista
  labels:
    app: quarkuscoffeeshop-barista
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-barista
  template:
    metadata:
      name: quarkuscoffeeshop-barista-deployment
      labels:
        app:  quarkuscoffeeshop-barista
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkuscoffeeshop-barista
        app.kubernetes.io/instance: quarkuscoffeeshop-barista
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkuscoffeeshop-barista
          image: jeremydavis/quarkuscoffeeshop-barista:{{ .Values.version.barista }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-counter
  labels:
    app: quarkuscoffeeshop-counter
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-counter
  template:
    metadata:
      name: quarkuscoffeeshop-counter-deployment
      labels:
        app:  quarkuscoffeeshop-counter
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkuscoffeeshop-counter
        app.kubernetes.io/instance: quarkuscoffeeshop-counter
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkuscoffeeshop-counter
          image: jeremydavis/quarkuscoffeeshop-counter:{{ .Values.version.counter }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
            - name: MONGO_DB
              value: cafedb
            - name: MONGO_URL
              value: mongodb://mongodb:mongodb@mongodb:27017/cafedb
            - name: MONGO_USERNAME
              value: mongodb
            - name: MONGO_PASSWORD
              value: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-customermocker
  labels:
    app: quarkuscoffeeshop-customermocker
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-customermocker
  template:
    metadata:
      name: quarkuscoffeeshop-customermocker-deployment
      labels:
        app:  quarkuscoffeeshop-customermocker
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkuscoffeeshop-customermocker
        app.kubernetes.io/instance: quarkuscoffeeshop-customermocker
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkuscoffeeshop-customermocker
          image: jeremydavis/quarkuscoffeeshop-customermocker:{{ .Values.version.customermocker }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REST_URL
              value: http://quarkuscoffeeshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeeshop-kitchen
  labels:
    app: quarkuscoffeeshop-kitchen
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-kitchen
  template:
    metadata:
      name: quarkuscoffeeshop-kitchen-deployment
      labels:
        app:  quarkuscoffeeshop-kitchen
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkuscoffeeshop-kitchen
        app.kubernetes.io/instance: quarkuscoffeeshop-kitchen
        app.kubernetes.io/part-of: quarkus-cafe
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkuscoffeeshop-kitchen
          image: jeremydavis/quarkuscoffeeshop-kitchen:{{ .Values.version.kitchen }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_URLS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkuscoffeshop-web
  labels:
    app: quarkuscoffeeshop-web
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkuscoffeeshop-web
  template:
    metadata:
      name: quarkuscoffeeshop-web
      labels:
        app: quarkuscoffeeshop-web
        release: {{ .Release.Name }}
        app.kubernetes.io/component: quarkuscoffeeshop-web
        app.kubernetes.io/instance: quarkuscoffeeshop-web
        app.kubernetes.io/part-of: quarkuscoffeeshop
        quarkus-cafe: ""
        app.openshift.io/runtime-namespace: {{ .Values.projectnamespace }}
    spec:
      containers:
        - name: quarkuscoffeeshop-web
          image: jeremydavis/quarkuscoffeeshop-web:{{ .Values.version.web }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka_cluster_name }}-kafka-bootstrap:9092
            - name: REST_URL
              value: http://quarkuscoffeeshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}
            - name: STREAM_URL
              value:  http://quarkuscoffeeshop-web-{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}/dashboard/stream
            - name: CORS_ORIGINS
              value: http://{{ .Values.projectnamespace }}.apps.{{ .Values.domain }}
